### ISSUE TITLE
TemplateEvents need priorities

### ISSUE THREAD

**Issue by enex** [exoplanetforum/board#2]
To determine which Event registerd by the Plugins will be rendered first it is necessary to introduce something like priorities for events.

**Comment by Padarom** [comment]
Template events are to be registered during the registration process of the Service Providers (Plugins are, in their core, Service Providers). This means, that as long as a plugin is enabled, its registered template events are known to the TemplateResolver instance.

We could use that to give both developers and forum owners the possibility to set the priority for when the view is going to be rendered. Obviously this is a more advanced option and isn't going to be needed on a day-by-day basis, but we could implement that in the backend given the following things apply:

- Restrict each plugin to only register one view per event (so the plugin namespace + event name are unique)
- Events are saved in the database, if the priority has been manually changed
- Developers can define a default priority

Does this sound reasonable?

**Comment by enex** [comment]
Sounds like a rather complete solution.

**Comment by Padarom** [comment]
Added with ba68affae20805a596cadc5141830736dee639dd (and [134dc12](https://github.com/exoplanetforum/atmosphere/commit/134dc1208b77587c1476074aa8672465b35b7f8f) on exoplanetforum/atmosphere). Just need to add a possibility to manually change the priorities in the ACP, but for that, there's a lot of things to be done first.

**Comment by Padarom** [comment]
I have thought about this again. Plugins could actually be able to just extend other tables, because these plugins have to be dependencies.

So if Plugin B depends on Plugin A and extends one of Plugin A's tables, Plugin A shouldn't be allowed to be uninstalled anyways, because there's plugins installed that depend on it.
